import "../styles/global.css";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import { ModeToggle, ThemeProvider } from "@/components/theme-provider";
import { NavigationBar } from "@/components/navigation_bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className="relative m-8  ">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavigationBar />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
