import "../app/global.css";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationBar } from "@/components/navigation_bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html className=" " lang="en">
     
      <head />
     
      <body className="m-0 flex flex-col p-0 bg-background min-h-screen font-sans antialiased">
      <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <NavigationBar />

          <main className=" container mx-auto flex-grow p-4">{children}

          <Button    className="mt-4">
            Button
          </Button>
          
          </main>
          </ThemeProvider>
      </body>
     
    </html>

  );
}
